puts"-------------------------------------------"
puts "Please choose the path from the following:"
puts "Left |||| Forward |||| Right"
puts "-------------------------------------------"
user = gets.chomp.downcase
if user == "left" 
  puts"-------------------------------------------"
  puts "Oh no! There is a werewolf, you died."
  puts"-------------------------------------------"
elsif user == "right" 
  puts"-------------------------------------------"
  puts "Oh no! There is a goblin, you died."
  puts"-------------------------------------------"
elsif user == "forward"
  puts"-------------------------------------------"
  puts "You proceed..."
  puts"-------------------------------------------"
  puts "Please choose the path from the following:"
  puts "Left |||| Forward |||| Right"
  puts "-------------------------------------------"
  user = gets.chomp.downcase
  if user == "forward"
    puts"-------------------------------------------"
    puts "You won!"
    puts"-------------------------------------------"
  elsif user == "left" 
    puts"-------------------------------------------"
    puts "Oh no! There is a werewolf, you died."
    puts"-------------------------------------------"
  elsif user == "right" 
    puts"-------------------------------------------"
    puts "Oh no! There is a goblin, you died."
    puts"-------------------------------------------"
  else 
    puts"-------------------------------------------"
    puts "Wrong input, try again!"  
    puts"-------------------------------------------"
  end
else 
  puts"-------------------------------------------"
  puts "Wrong input, try again!"  
  puts"-------------------------------------------"  
end